# Copyright (c) Vadim Pavlov 2026. Licensed under GPL-3.0.

"""Generator orchestrator for VPN007.

Coordinates all individual generators (compose, nginx, xray, nftables,
blocklist updater, hostname resolver, forwarding, docs, clients) to
produce the complete set of deployment artifacts.  The main entry point
is :func:`generate_all`, which creates the output directory structure,
calls each generator, writes files, and returns a mapping of relative
paths to their content.
"""

from __future__ import annotations

import logging
from pathlib import Path

from vpn007.blocklist import generate_blocklist_updater
from vpn007.clients import provision_awg_peer, provision_xray_client
from vpn007.compose import generate_compose
from vpn007.docs import generate_docs
from vpn007.exit_node import generate_exit_node_configs
from vpn007.firewall import generate_nftables_config
from vpn007.forwarding import generate_forwarding_script
from vpn007.hostname_resolver import generate_hostname_resolver
from vpn007.models import DeployConfig
from vpn007.nginx import generate_nginx_http_config, generate_nginx_stream_config
from vpn007.xray import generate_xray_config

logger = logging.getLogger(__name__)

# Subdirectories created inside the output directory.
_OUTPUT_SUBDIRS: list[str] = [
    "nginx",
    "xray",
    "scripts",
    "systemd",
    "docs",
    "clients",
    "exit-node",
    "data/three_x_ui",
    "data/amneziawg",
    "data/tailscale",
    "data/letsencrypt",
    "data/certbot_webroot",
]


def generate_initial_approved_ips_conf(config: DeployConfig) -> str:
    """Generate initial ``approved_panel_ips.conf`` from static approved IPs.

    Produces Nginx ``allow`` directives for each entry in
    ``config.approved_ips``.  This file must exist before Nginx starts
    because the HTTP config uses an ``include`` directive that references
    it.  The hostname resolver updates this file later with dynamically
    resolved addresses.

    Parameters
    ----------
    config:
        The validated deployment configuration.

    Returns
    -------
    str
        Content for ``approved_panel_ips.conf`` with ``allow`` directives.
    """
    lines: list[str] = [
        "# approved_panel_ips.conf — auto-generated by VPN007",
        "# Updated by hostname-resolver.sh at runtime.",
        "#",
        "# © Vadim Pavlov 2026",
        "",
    ]
    for ip in config.approved_ips:
        lines.append(f"allow {ip};")
    # Always include at least a comment so the file is never empty,
    # which would cause Nginx to reject the include.
    if not config.approved_ips:
        lines.append("# No static approved IPs configured.")
    lines.append("")
    return "\n".join(lines)


def _create_output_dirs(output_dir: Path) -> None:
    """Create the output directory structure.

    Creates ``output_dir`` and all required subdirectories.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    for subdir in _OUTPUT_SUBDIRS:
        (output_dir / subdir).mkdir(parents=True, exist_ok=True)
    logger.info("Created output directory structure at %s", output_dir)


def _copy_awg_build_files(output_dir: Path, files: dict[str, str]) -> None:
    """Copy AmneziaWG custom image build files to the output directory.

    Copies ``Dockerfile.amneziawg`` and ``docker-entrypoint-awg.sh`` from
    the project root into the output directory so that
    ``docker compose build amneziawg`` works from the deploy directory.
    """
    import shutil

    # Locate project root (where Dockerfile.amneziawg lives)
    project_root = Path(__file__).parent.parent.parent

    dockerfile_src = project_root / "Dockerfile.amneziawg"
    entrypoint_src = project_root / "docker-entrypoint-awg.sh"

    for src, filename in [
        (dockerfile_src, "Dockerfile.amneziawg"),
        (entrypoint_src, "docker-entrypoint-awg.sh"),
    ]:
        if src.is_file():
            content = src.read_text(encoding="utf-8")
            files[filename] = content
            _write_file(output_dir / filename, content)
        else:
            logger.warning(
                "AmneziaWG build file not found: %s — "
                "custom image build may fail.",
                src,
            )


def _write_file(path: Path, content: str) -> None:
    """Write *content* to *path*, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    logger.debug("Wrote %s (%d bytes)", path, len(content))


def generate_all(config: DeployConfig) -> dict[str, str]:
    """Generate all deployment artifacts and write them to *config.output_dir*.

    Calls every individual generator, writes the resulting files to the
    output directory, and returns a dict mapping relative file paths
    (relative to ``config.output_dir``) to their content.

    The generated artifacts include:

    - ``docker-compose.yml``
    - ``nginx/stream.conf``, ``nginx/http.conf``,
      ``nginx/approved_panel_ips.conf``
    - ``xray/config.json``
    - ``nftables.conf``
    - ``scripts/blocklist-updater.sh``,
      ``systemd/blocklist-updater.service``,
      ``systemd/blocklist-updater.timer``
    - ``scripts/hostname-resolver.sh``,
      ``systemd/hostname-resolver.service``,
      ``systemd/hostname-resolver.timer``
    - ``scripts/certbot-renew.sh``,
      ``systemd/certbot-renew.service``,
      ``systemd/certbot-renew.timer``
    - ``forwarding-install.py`` (only when forwarding is enabled)
    - ``docs/README.md``, ``docs/troubleshooting.md``,
      ``docs/client-guides.md``
    - ``clients/xray-{name}.txt``

    Parameters
    ----------
    config:
        The validated deployment configuration.

    Returns
    -------
    dict[str, str]
        Mapping of relative paths to file content.
    """
    output_dir = config.output_dir
    files: dict[str, str] = {}

    # 1. Create output directory structure
    _create_output_dirs(output_dir)

    # 2. Docker Compose
    logger.info("Generating docker-compose.yml...")
    compose_content = generate_compose(config)
    files["docker-compose.yml"] = compose_content
    _write_file(output_dir / "docker-compose.yml", compose_content)

    # 3. Nginx stream config (L4)
    logger.info("Generating nginx/stream.conf...")
    stream_conf = generate_nginx_stream_config(config)
    files["nginx/stream.conf"] = stream_conf
    _write_file(output_dir / "nginx" / "stream.conf", stream_conf)

    # 4. Nginx HTTP config (L7)
    logger.info("Generating nginx/http.conf...")
    http_conf = generate_nginx_http_config(config)
    files["nginx/http.conf"] = http_conf
    _write_file(output_dir / "nginx" / "http.conf", http_conf)

    # 5. Initial approved_panel_ips.conf (must exist before Nginx starts)
    logger.info("Generating nginx/approved_panel_ips.conf...")
    approved_ips_conf = generate_initial_approved_ips_conf(config)
    files["nginx/approved_panel_ips.conf"] = approved_ips_conf
    _write_file(output_dir / "nginx" / "approved_panel_ips.conf", approved_ips_conf)

    # 6. Xray config
    logger.info("Generating xray/config.json...")
    xray_conf = generate_xray_config(config)
    files["xray/config.json"] = xray_conf
    _write_file(output_dir / "xray" / "config.json", xray_conf)

    # 7. nftables firewall config
    logger.info("Generating nftables.conf...")
    nftables_conf = generate_nftables_config(config)
    files["nftables.conf"] = nftables_conf
    _write_file(output_dir / "nftables.conf", nftables_conf)

    # 8. Blocklist updater (script + systemd units)
    logger.info("Generating blocklist updater...")
    bl_script, bl_service, bl_timer = generate_blocklist_updater(config)
    files["scripts/blocklist-updater.sh"] = bl_script
    files["systemd/blocklist-updater.service"] = bl_service
    files["systemd/blocklist-updater.timer"] = bl_timer
    _write_file(output_dir / "scripts" / "blocklist-updater.sh", bl_script)
    _write_file(output_dir / "systemd" / "blocklist-updater.service", bl_service)
    _write_file(output_dir / "systemd" / "blocklist-updater.timer", bl_timer)

    # 9. Hostname resolver (script + systemd units)
    logger.info("Generating hostname resolver...")
    hr_script, hr_service, hr_timer = generate_hostname_resolver(config)
    files["scripts/hostname-resolver.sh"] = hr_script
    files["systemd/hostname-resolver.service"] = hr_service
    files["systemd/hostname-resolver.timer"] = hr_timer
    _write_file(output_dir / "scripts" / "hostname-resolver.sh", hr_script)
    _write_file(output_dir / "systemd" / "hostname-resolver.service", hr_service)
    _write_file(output_dir / "systemd" / "hostname-resolver.timer", hr_timer)

    # 10. Certbot renewal (script + systemd units)
    logger.info("Generating certbot renewal scripts...")
    certbot_script, certbot_service, certbot_timer = _generate_certbot_renew(config)
    files["scripts/certbot-renew.sh"] = certbot_script
    files["systemd/certbot-renew.service"] = certbot_service
    files["systemd/certbot-renew.timer"] = certbot_timer
    _write_file(output_dir / "scripts" / "certbot-renew.sh", certbot_script)
    _write_file(output_dir / "systemd" / "certbot-renew.service", certbot_service)
    _write_file(output_dir / "systemd" / "certbot-renew.timer", certbot_timer)

    # 11. Forwarding script (only when enabled)
    if config.forwarding_enabled:
        logger.info("Generating forwarding-install.py...")
        fwd_script = generate_forwarding_script(config)
        files["forwarding-install.py"] = fwd_script
        _write_file(output_dir / "forwarding-install.py", fwd_script)

    # 11b. Exit node role configs (only when enabled)
    if config.exit_node_enabled:
        logger.info("Generating exit-node role configuration...")
        exit_node_files = generate_exit_node_configs(config)
        for rel_path, content in exit_node_files.items():
            files[rel_path] = content
            _write_file(output_dir / rel_path, content)

    # 12. Documentation
    logger.info("Generating documentation...")
    doc_files = generate_docs(config)
    for doc_name, doc_content in doc_files.items():
        rel_path = f"docs/{doc_name}"
        files[rel_path] = doc_content
        _write_file(output_dir / "docs" / doc_name, doc_content)

    # 13. Xray client provisioning
    logger.info("Provisioning initial Xray client...")
    xray_client = provision_xray_client(config, client_name=config.xray_initial_client)
    client_filename = f"xray-{xray_client.client_name}.txt"
    client_content = xray_client.vless_share_link + "\n"
    files[f"clients/{client_filename}"] = client_content
    _write_file(output_dir / "clients" / client_filename, client_content)

    # 14. AmneziaWG peer provisioning
    logger.info("Provisioning initial AmneziaWG peer...")
    awg_peer = provision_awg_peer(config, peer_name=config.awg_initial_peer)
    awg_filename = f"awg-{awg_peer.peer_name}.conf"
    awg_content = awg_peer.conf_content + "\n"
    files[f"clients/{awg_filename}"] = awg_content
    _write_file(output_dir / "clients" / awg_filename, awg_content)

    logger.info(
        "Generated %d files in %s", len(files), output_dir,
    )

    return files


def _generate_certbot_renew(
    config: DeployConfig,
) -> tuple[str, str, str]:
    """Generate certbot renewal script, service unit, and timer unit.

    Parameters
    ----------
    config:
        The validated deployment configuration.

    Returns
    -------
    tuple[str, str, str]
        A 3-tuple of (script_content, service_unit, timer_unit).
    """
    from jinja2 import Environment, FileSystemLoader, select_autoescape

    templates_dir = Path(__file__).parent / "templates"
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=select_autoescape([]),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    scripts_dir = str(config.output_dir / "scripts")
    compose_dir = str(config.output_dir)

    script_template = env.get_template("certbot-renew.sh.j2")
    script = script_template.render(
        compose_dir=compose_dir,
    )

    service_template = env.get_template("certbot-renew.service.j2")
    service = service_template.render(scripts_dir=scripts_dir)

    timer_template = env.get_template("certbot-renew.timer.j2")
    timer = timer_template.render()

    return script, service, timer


def generate_deployment_summary(
    config: DeployConfig,
    files: dict[str, str],
) -> str:
    """Generate a deployment summary listing service endpoints and credentials.

    Parameters
    ----------
    config:
        The validated deployment configuration.
    files:
        The dict of generated file paths returned by :func:`generate_all`.

    Returns
    -------
    str
        A formatted summary string suitable for console output.
    """
    server = config.domain
    lines: list[str] = [
        "",
        "=" * 60,
        "  VPN007 — Deployment Summary",
        "=" * 60,
        "",
        "Service Endpoints:",
        f"  HTTPS:           https://{server}/",
    ]
    if config.enable_port_8443:
        lines.append(f"  HTTPS (alt):     https://{server}:8443/")
    lines.append(f"  3x-ui Panel:     https://{server}{config.xui_path_prefix}/")
    lines.append(f"  AWG Panel:       https://{server}{config.awg_panel_path_prefix}/")
    if config.awg_listen_port is not None:
        lines.append(f"  AmneziaWG (UDP): {server}:{config.awg_listen_port}")
    lines.append("")
    lines.append("Generated Files:")
    for rel_path in sorted(files.keys()):
        lines.append(f"  {config.output_dir / rel_path}")
    lines.append("")
    if config.approved_ips:
        lines.append("Approved Panel IPs:")
        for ip in config.approved_ips:
            lines.append(f"  {ip}")
        lines.append("")
    if config.approved_hostnames:
        lines.append("Approved Panel Hostnames:")
        for hostname in config.approved_hostnames:
            lines.append(f"  {hostname}")
        lines.append("")
    lines.append("=" * 60)
    lines.append("")
    return "\n".join(lines)
