# Copyright (c) Vadim Pavlov 2026. Licensed under GPL-3.0.

"""Data models for VPN007 deployment configuration and results."""

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path


class TunnelType(Enum):
    """Supported tunnel types for inter-VM encrypted forwarding."""

    WIREGUARD = "wireguard"
    SSH = "ssh"
    TAILSCALE = "tailscale"
    XRAY = "xray"


class ForwardingMode(Enum):
    """Forwarding mode for inter-VM traffic."""

    PORTS = "ports"  # Forward specific ports via DNAT (default)
    ALL = "all"  # Route all VPN client traffic through the tunnel


class CoverSiteMode(Enum):
    """Cover site serving mode."""

    STATIC = "static"  # Serve local static files
    PROXY = "proxy"  # Reverse proxy to external site


@dataclass
class AwgObfuscation:
    """AmneziaWG 2.0 obfuscation parameters."""

    # Packet size parameters (must match between server and clients)
    s1: int  # Random prefix for Init packets (0-1132, recommended 15-150)
    s2: int  # Random prefix for Response packets (0-1188, recommended 15-150)
    s3: int  # Random prefix for Cookie packets (0-1216, recommended 15-150)
    s4: int  # Random prefix for Data packets (0-32)
    # Dynamic headers for packet types (AmneziaWG 2.0: ranges like "min-max")
    # All H values must be non-overlapping ranges in [5, 2147483647].
    h1: str  # Dynamic header range for Init packets
    h2: str  # Dynamic header range for Response packets
    h3: str  # Dynamic header range for Cookie packets
    h4: str  # Dynamic header range for Data packets
    # Junk packet parameters (can differ between server and clients)
    jc: int = 4  # Junk packet count (1-128, recommended 4-10)
    jmin: int = 50  # Min junk packet size (0-1280)
    jmax: int = 1000  # Max junk packet size (0-1280, Jmin < Jmax)
    # CPS signature packets (optional, CPS format hex-blob strings)
    # When auto-generated by generate_awg_obfuscation(), these default to
    # WebRTC/STUN signatures. The empty string default here is for manual
    # construction — the generator always fills I1-I3 with STUN patterns.
    # See: https://docs.amnezia.org/documentation/amnezia-wg/
    i1: str = ""  # Signature packet 1 (CPS format)
    i2: str = ""  # Signature packet 2 (CPS format)
    i3: str = ""  # Signature packet 3 (CPS format)
    i4: str = ""  # Signature packet 4 (CPS format)
    i5: str = ""  # Signature packet 5 (CPS format)


@dataclass
class PortForward:
    """A single port forwarding rule for inter-VM traffic."""

    protocol: str  # "tcp" or "udp"
    listen_port: int  # Port on primary VM
    forward_port: int  # Port on secondary VM
    description: str = ""


@dataclass
class RealityKeys:
    """Xray Reality key pair."""

    private_key: str
    public_key: str
    short_id: str  # 8-char hex


@dataclass
class XrayClientConfig:
    """Generated Xray VLESS+Reality client configuration."""

    client_name: str
    uuid: str
    vless_share_link: str  # vless://... URI for client import
    qr_code_data: str  # Data string for QR code generation
    reality_public_key: str
    short_id: str
    sni: str
    server_address: str
    server_port: int


@dataclass
class AwgPeerConfig:
    """Generated AmneziaWG peer configuration."""

    peer_name: str
    private_key: str
    public_key: str
    preshared_key: str | None
    allowed_ips: str
    endpoint: str
    conf_content: str  # Full .conf file content for client import


@dataclass
class TunnelConfig:
    """Configuration for an encrypted inter-VM tunnel."""

    tunnel_type: TunnelType
    primary_ip: str
    secondary_ip: str
    reverse_initiated: bool
    # WireGuard/AmneziaWG specific
    wg_private_key: str | None = None
    wg_public_key: str | None = None
    wg_peer_public_key: str | None = None
    wg_listen_port: int = 51821
    wg_tunnel_subnet: str = "10.99.0.0/30"
    # SSH specific
    ssh_key_path: str | None = None
    ssh_port: int = 22
    autossh_monitor_port: int = 20000
    # Tailscale specific
    tailscale_primary_hostname: str | None = None
    tailscale_secondary_hostname: str | None = None
    # Reconnection
    reconnect_initial_delay: int = 5
    reconnect_max_delay: int = 300


@dataclass
class DeployConfig:
    """Complete validated deployment configuration."""

    # General
    domain: str
    reality_sni: str = "www.microsoft.com"
    cover_site_mode: CoverSiteMode = CoverSiteMode.STATIC
    cover_site_url: str | None = None
    cover_site_static_path: Path | None = None

    # Routing paths
    xui_path_prefix: str = "/secretpanel"  # Randomized at load time if not set
    awg_panel_path_prefix: str = "/awgadmin"  # Randomized at load time if not set
    enable_port_8443: bool = False

    # Xray / Reality
    xray_internal_port: int = 10443
    reality_keys: RealityKeys | None = None

    # AmneziaWG
    awg_listen_port: int | None = None
    awg_obfuscation: AwgObfuscation | None = None
    awg_panel_port: int = 51821

    # Tailscale
    tailscale_auth_key: str | None = None
    tailscale_hostname: str | None = None  # TS_HOSTNAME for tailnet identity
    tailscale_extra_args: str = "--advertise-exit-node"  # TS_EXTRA_ARGS

    # Multi-IP
    incoming_ip: str | None = None
    outgoing_ip: str | None = None
    public_ipv4: str | None = None
    public_ipv6: str | None = None

    # TLS configuration
    tls_versions: list[str] = field(default_factory=lambda: ["1.2", "1.3"])
    skip_certbot: bool = False  # Skip Let's Encrypt; keep self-signed cert
    https_port: int = 443  # Main HTTPS listen port (change for staging/lab)

    # Access control
    approved_ips: list[str] = field(default_factory=list)
    approved_hostnames: list[str] = field(default_factory=list)
    ssh_approved_ips: list[str] = field(default_factory=list)
    ssh_approved_hostnames: list[str] = field(default_factory=list)
    hostname_resolve_interval_min: int = 30

    # AS/Subnet blocking
    blocked_as_numbers: list[str] = field(default_factory=list)
    blocked_subnets: list[str] = field(default_factory=list)
    blocklist_update_interval_hours: int = 6

    # Forwarding
    forwarding_enabled: bool = False
    forwarding_mode: ForwardingMode = ForwardingMode.PORTS
    tunnel_type: TunnelType | None = None
    exit_node_host: str | None = None
    reverse_initiated: bool = False
    forwarding_ports: list[PortForward] = field(default_factory=list)
    reconnect_initial_delay_sec: int = 5
    reconnect_max_delay_sec: int = 300
    tunnel_subnet: str = "10.99.0.0/30"  # Point-to-point tunnel subnet
    # Xray tunnel specific (used when tunnel_type=xray)
    tunnel_xray_sni: str | None = None  # SNI for inter-node Reality (defaults to reality_sni)
    tunnel_xray_port: int = 443  # Port on exit node for VLESS+Reality tunnel

    # Exit node role (dual-role: this VM also serves as exit node for another)
    exit_node_enabled: bool = False
    exit_node_tunnel_type: TunnelType | None = None
    exit_node_peer_host: str | None = None  # IP or hostname of the VM forwarding traffic to us
    exit_node_tunnel_subnet: str = "10.99.1.0/30"  # Different subnet from primary tunnel
    exit_node_listen_port: int = 51822  # WG listen port for exit-node tunnel
    exit_node_reverse_initiated: bool = False

    # Initial clients
    xray_initial_client: str = "default-client"
    awg_initial_peer: str = "default-peer"

    # Output
    output_dir: Path = Path("./deploy")
    deployment_log_path: Path = Path("./deploy/deploy.log")


class DeployError(Exception):
    """Base error with context for structured logging."""

    def __init__(
        self,
        service: str,
        step: str,
        message: str,
        remediation: str | None = None,
    ):
        self.service = service
        self.step = step
        self.message = message
        self.remediation = remediation
        super().__init__(f"[{service}] {step}: {message}")


@dataclass
class ServiceResult:
    """Result of deploying a single service."""

    success: bool
    error: DeployError | None = None


@dataclass
class DeployResult:
    """Result of the full deployment."""

    services: dict[str, ServiceResult] = field(default_factory=dict)
